### ISSUE TITLE
Open payments do not stay after server restart

### ISSUE THREAD

**Issue by ogcatt** [busyboredom/acceptxmr#53]
Do I need to create a custom storage (in the build function) to make invoices persistant? Or is it a misconfiguration? Thanks.

**Comment by busyboredom** [comment]
Hey, any of the built-in storage options other than `InMemory` should be persistent. Are you using `InMemory`?

If you are using `InMemory`, could you try with the `Sqlite` store and let me know if that fixes your issue?

**Comment by busyboredom** [comment]
Added an example here: https://github.com/busyboredom/acceptxmr/blob/dc4d1acb9e82c7276aacb1ed54413695ee459acb/examples/persistence/main.rs

**Comment by ogcatt** [comment]
I am getting a dependency conflict because I am using seaorm which requires libsqlite3-sys v0.24.2, but acceptxmr requires sqlite3-sys v0.14.0... I am not sure how to fix this 😔

**Comment by busyboredom** [comment]
Got it, yeah that was your problem then. `InMemory` means stored in RAM, so it's not persistent.

Hmm, yep looks the sqlite crate used by AcceptXMR hasn't kept their sqlite3-sys dependency up-to-date... that's not very cool, I'll see about fixing that. 

Your options in the meantime:
* Use the `Sled` store instead of the `Sqlite` one (you'll need to enable the `sled` feature). This is probably your easiest option.
* Implement a custom `InvoiceStorage` using another DB crate of your choosing. Since you're already pulling in `sqlx` from seaorm, maybe using sqlx here would be elegant. This is more work than the first option but gives you the most flexibility.
