### ISSUE TITLE
Issue with using acceptxmr in rocket project

### ISSUE THREAD

**Issue by ogcatt** [busyboredom/acceptxmr#63]
I have been using acceptxmr for my site, however two customer transactions failed out of the blue, and I am not sure why as my code worked previously when testing it.

I kept the rust application up for three weeks. After approx 10 days, I stopped getting any logs (for two weeks) from acceptxmr, and this is the last log I recieved from the library:

```
[2023-05-23T17:18:22Z WARN  acceptxmr::payment_gateway] Removed an invoice which was neither expired, nor fully confirmed and a block or more old. Was this intentional?
```

Before then I was getting semi-often errors to do with HTTP deadline elapsing.
Do you know why this could happen? Is it because the library was active for a long time?

**Comment by busyboredom** [comment]
> Removed an invoice which was neither expired, nor fully confirmed and a block or more old. Was this intentional?

This warning is logged when an invoice is removed from the DB (using the `remove_invoice(...)` method) before it was confirmed or expired. Is it possible that some logic in your code is removing invoices prematurely? That would also explain why two of your customers reported failed transactions.

> HTTP deadline elapsing

This happens when the monero node you are using takes too long to respond. AcceptXMR should always recover gracefully from these errors by catching back up once a connection to the node is reestablished. 

>  Is it because the library was active for a long time?

Running for a long time shouldn't be an issue, I've run my instance for several months at a time without any problems like this. When the logs stopped, was the rust application still running or had it crashed?

**Comment by ogcatt** [comment]
The rust application was still running when the logs topped

**Comment by ogcatt** [comment]
Wait actually not all logs stopped, on payment I made a message printing the status of the invoice, so the invoice item existed, but no confirmations or payments were detected, so it seems only the payment checker stopped rather than the invoices being deleted.

**Comment by busyboredom** [comment]
Interesting, sounds like the scanning thread panicked, that's not cool at all. When you stopped the rust application, were there any interesting logs on shutdown?

There is [a method for checking on the status of the scanning thread](https://docs.rs/acceptxmr/0.12.0/acceptxmr/struct.PaymentGateway.html#method.status), you could use it to ensure the thread is healthy and then call `run()` again to restart it on error. I feel bad giving this to you as a "solution" because that thread _should_ be entirely free of panics, but if you logged any errors returned by the status method it would be very helpful for debugging this issue.

**Comment by ogcatt** [comment]
There were not any interesting logs on shutdown.

I use a clone of the monero payment gateway as I have one for management (e.g removing invoices when the user manually closes a payment), and I have another for checking invoice updates in a seperate thread before I launch rocket. I may have to check the status of both.

**Comment by ogcatt** [comment]
Part of my code looks like this:

```rs
let mut subscriber = gateway_copy.subscribe_all();
info!("Setup gateway copy DB");
loop {
    let Some(invoice) = subscriber.recv().await else { panic!("Blockchain scanner crashed!") };
    info!("Received invoice update: {:?}", invoice);
    //...
}

With that I tried to open a payment on my site. After I saw on exploremonero that It had confirmations this is what I get:

```
Received invoice update: Invoice { address: "...", index: SubIndex { major: 0, minor: 0 }, creation_height: ..., amount_requested: ..., amount_paid: 0, paid_height: None, confirmations_required: 10, current_height: ..., expiration_height: ..., transfers: [], description: "admin" }
```
(... is what I replaced, these values are normal)

My custom check also looks like this:

```
xmrpaid: 0.0 (out of 0.076130997911 xmr requested) / picospaid: 0 (out of 76130997911 picos requested) / expirationin: 246 / confirmations: None (out of 10 confirmations required) / isconfirmed: false / isexpired false
```

Even after confirmations it does not show any payments coming in, only some periodic updates? I am confused because this worked previously.

![image](https://github.com/busyboredom/acceptxmr/assets/119142199/a96a324b-65a4-473a-be2a-55dd53e710ca)
![image](https://github.com/busyboredom/acceptxmr/assets/119142199/5f68baa9-c1e9-4fd6-b499-87fe88938970)
![image](https://github.com/busyboredom/acceptxmr/assets/119142199/0f8f952e-2663-4f3e-b8d3-2a73c5902cc6)

**Comment by busyboredom** [comment]
Hmm, very weird. Could you try a different node? Maybe `node.sethforprivacy.com:18089`? 

Are you sending transactions from a normal wallet (i.e. cakewallet, the official GUI, feather, monerujo...)? Asking because transactions with timelocks are intentionally ignored to avoid abuse, so if you're adding timelocks then that could cause this.

**Comment by ogcatt** [comment]
I am sending transactions from mymonero wallet (from a different address).

I switched the node and it fixed it. Not sure what was wrong with sethforprivacy, maybe they blocked my server or maybe they are just bugged at the moment.

Thanks for all the help.
